import type { Metadata } from 'next';
import './globals.css';

import Nav from '@/components/Nav';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
    title: 'Pro Talks',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <Nav />
                    <div>{children}</div>
                </body>
            </html>
        </ClerkProvider>
    );
}
