import type { Metadata } from 'next';
import './globals.css';

import Nav from '@/components/Nav';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
    title: 'Pro Talks',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <body className="flex flex-col h-screen">
                    <Nav />
                    <div className="flex-1 w-full justify-center items-center flex">{children}</div>
                </body>
            </html>
        </ClerkProvider>
    );
}
